import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";

const robotoBlack = localFont({
  src: "./fonts/RobotoBlack.woff",
  variable: "--font-roboto-black",
  weight: "900",
});

const robotoBold = localFont({
  src: "./fonts/RobotoBold.woff",
  variable: "--font-roboto-bold",
  weight: "700",
});

const robotoMedium = localFont({
  src: "./fonts/RobotoMedium.woff",
  variable: "--font-roboto-medium",
  weight: "500",
});

const robotoRegular = localFont({
  src: "./fonts/RobotoRegular.woff",
  variable: "--font-roboto-regular",
  weight: "400",
});

const robotoLight = localFont({
  src: "./fonts/RobotoLight.woff",
  variable: "--font-roboto-light",
  weight: "300",
});

const robotoThin = localFont({
  src: "./fonts/RobotoThin.woff",
  variable: "--font-roboto-thin",
  weight: "100",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${robotoBlack.variable} ${robotoBold.variable} ${robotoMedium.variable} ${robotoRegular.variable} ${robotoLight.variable} ${robotoThin.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
